#!/usr/bin/env bash
# Export browser cookies for GravityDesktop / gravity-serve / yt-dlp.
# Produces Netscape cookies.txt (works without python3-secretstorage).
set -euo pipefail

APP_DIR="$(cd "$(dirname "$0")" && pwd)"
COOKIES_DIR="${HOME}/.config/gravity-desktop"
COOKIES_FILE="${GRAVITY_COOKIES_FILE:-${COOKIES_DIR}/cookies.txt}"
PROBE_URL="${GRAVITY_COOKIES_PROBE_URL:-https://www.youtube.com/watch?v=jNQXAC9IVRw}"

if [[ -x "${APP_DIR}/yt-dlp" ]]; then
  YTDLP="${APP_DIR}/yt-dlp"
elif [[ -x "${HOME}/Downloads/GravityDesktop/yt-dlp" ]]; then
  YTDLP="${HOME}/Downloads/GravityDesktop/yt-dlp"
else
  YTDLP="${YTDLP_PATH:-$(command -v yt-dlp || true)}"
fi
if [[ -z "${YTDLP}" || ! -x "${YTDLP}" ]]; then
  echo "ERROR: yt-dlp not found. Set YTDLP_PATH or place yt-dlp in ${APP_DIR}" >&2
  exit 1
fi

# yt-dlp supported: brave chrome chromium edge firefox opera safari vivaldi whale
SUPPORTED=(brave chrome chromium edge firefox opera vivaldi whale safari)

browser_cookie_db() {
  local b="$1" home="${HOME}"
  case "${b,,}" in
    brave)     [[ -f "${home}/.config/BraveSoftware/Brave-Browser/Default/Cookies" ]] ;;
    chromium)  [[ -f "${home}/.config/chromium/Default/Cookies" ]] ;;
    chrome)    [[ -f "${home}/.config/google-chrome/Default/Cookies" ]] ;;
    edge)      [[ -f "${home}/.config/microsoft-edge/Default/Cookies" ]] ;;
    opera)     [[ -f "${home}/.config/opera/Default/Cookies" || -f "${home}/.config/opera-stable/Default/Cookies" ]] ;;
    vivaldi)   [[ -f "${home}/.config/vivaldi/Default/Cookies" ]] ;;
    whale)     [[ -f "${home}/.config/naver-whale/Default/Cookies" || -f "${home}/.config/Naver Whale/Default/Cookies" ]] ;;
    safari)    [[ -f "${home}/Library/Cookies/Cookies.binarycookies" ]] || [[ -d "${home}/Library/Safari" ]] ;;
    firefox)
      for base in "${home}/snap/firefox/common/.mozilla/firefox" "${home}/.mozilla/firefox"; do
        [[ -d "${base}" ]] || continue
        for prof in "${base}"/*; do
          [[ -d "${prof}" && -f "${prof}/cookies.sqlite" ]] && return 0
        done
      done
      return 1
      ;;
    *) return 1 ;;
  esac
}

list_detected() {
  echo "Detected browsers (cookie DB present):"
  local any=0
  for b in "${SUPPORTED[@]}"; do
    if browser_cookie_db "${b}"; then
      echo "  ✓ ${b}"
      any=1
    fi
  done
  if [[ "${any}" -eq 0 ]]; then
    echo "  (none — log into YouTube in a browser first, or use a cookies.txt export extension)"
  fi
  echo ""
  echo "All yt-dlp-supported browsers: ${SUPPORTED[*]}"
}

usage() {
  cat <<EOF
Usage: $(basename "$0") [browser] [options]

Export login cookies for age-restricted / private downloads (avoids HTTP 403).

Options:
  --list              Show which browsers are detected on this machine
  --use-browser       Write GRAVITY_COOKIES_BROWSER to ${COOKIES_DIR}/env
                      (live browser DB; needs python3-secretstorage on Linux)
  --file-only         Only write cookies.txt (default)
  -o PATH             Output cookies file (default: ${COOKIES_FILE})
  -h, --help          This help

Examples:
  $(basename "$0") --list
  $(basename "$0") chrome              # export Chrome → cookies.txt
  $(basename "$0") firefox --use-browser
  $(basename "$0") opera -o ~/cookies.txt

After export, restart gravity-serve / GravityDesktop. cookies.txt takes priority
over GRAVITY_COOKIES_BROWSER when both exist.

Linux Chromium decrypt: sudo apt install python3-secretstorage
Or use this script to build cookies.txt (no secretstorage needed).
EOF
}

export_cookies() {
  local browser="$1" out="$2"
  mkdir -p "$(dirname "${out}")"
  echo "Exporting cookies from ${browser} → ${out}"
  echo "  (probe: ${PROBE_URL})"
  if ! "${YTDLP}" \
    --cookies-from-browser "${browser}" \
    --cookies "${out}" \
    --skip-download \
    --print "%(title)s" \
    "${PROBE_URL}" >/dev/null 2>&1; then
    echo "ERROR: cookie export failed for '${browser}'." >&2
    echo "  • Close the browser or use a copy profile" >&2
    echo "  • Chromium: sudo apt install python3-secretstorage" >&2
    echo "  • Or export manually with a 'Get cookies.txt' browser extension" >&2
    exit 1
  fi
  if [[ ! -s "${out}" ]]; then
    echo "ERROR: ${out} is empty" >&2
    exit 1
  fi
  echo "OK: $(wc -l < "${out}") lines → ${out}"
}

write_env_browser() {
  local browser="$1"
  mkdir -p "${COOKIES_DIR}"
  local envfile="${COOKIES_DIR}/env"
  {
    echo "# Generated by setup-cookies.sh — source before run.sh / gravity-serve"
    echo "export GRAVITY_COOKIES_BROWSER=${browser}"
    echo "# unset GRAVITY_COOKIES_FILE to prefer live browser over cookies.txt"
  } > "${envfile}"
  echo "Wrote ${envfile} (run: source ${envfile})"
}

MODE="file"
BROWSER=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    -h|--help) usage; exit 0 ;;
    --list) list_detected; exit 0 ;;
    --use-browser) MODE="browser"; shift ;;
    --file-only) MODE="file"; shift ;;
    -o) COOKIES_FILE="$2"; shift 2 ;;
    -*) echo "Unknown option: $1" >&2; usage; exit 1 ;;
    *) BROWSER="$1"; shift ;;
  esac
done

if [[ -z "${BROWSER}" ]]; then
  list_detected
  echo "Pick a browser to export cookies from:"
  for b in "${SUPPORTED[@]}"; do
    browser_cookie_db "${b}" && echo "  ${b}"
  done
  echo ""
  read -r -p "Browser name [chrome]: " BROWSER
  BROWSER="${BROWSER:-chrome}"
fi

BROWSER="${BROWSER,,}"
valid=0
for b in "${SUPPORTED[@]}"; do
  [[ "${b}" == "${BROWSER}" ]] && valid=1 && break
done
if [[ "${valid}" -eq 0 ]]; then
  echo "ERROR: unsupported browser '${BROWSER}'. Use: ${SUPPORTED[*]}" >&2
  exit 1
fi

if [[ "${MODE}" == "file" ]]; then
  export_cookies "${BROWSER}" "${COOKIES_FILE}"
  echo ""
  echo "Next: restart services so they pick up cookies.txt"
  echo "  source is automatic if ${COOKIES_FILE} exists (file beats browser DB)"
elif [[ "${MODE}" == "browser" ]]; then
  write_env_browser "${BROWSER}"
  echo "Use live browser cookies (enable Private checkbox in GravityDesktop for some URLs)"
fi